use super::{
    entity_type_map::PCC_EMIT_ORDER,
    plan::{FilePlan, SourcePlan},
};

/// Generate the content of the PCC file for a source.
pub fn generate_pcc(source_plan: &SourcePlan) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("# Generated by artisan-pcgen".to_string());
    lines.push(String::new());

    // Source metadata line.
    lines.push(format!(
        "SOURCELONG:{}\tSOURCESHORT:{}\tSOURCEDATE:{}",
        source_plan.source_title,
        source_plan.abbreviation.to_ascii_uppercase(),
        "" // date not tracked in SourceRecord today
    ));
    lines.push(String::new());

    lines.push(format!("GAMEMODE:{}", source_plan.gamemode));
    lines.push(String::new());

    // Build a lookup: file_suffix → FilePlan
    let file_by_suffix: std::collections::HashMap<&str, &FilePlan> = source_plan
        .files
        .iter()
        .map(|f| (f.file_suffix.as_str(), f))
        .collect();

    // Emit PCC lines in canonical order, only for files that have entities.
    for (suffix, pcc_token) in PCC_EMIT_ORDER {
        // Check exact suffix and also suffix_other / suffix_<label> variants.
        let matching_files: Vec<&FilePlan> = source_plan
            .files
            .iter()
            .filter(|f| f.file_suffix == *suffix || f.file_suffix.starts_with(&format!("{suffix}_")))
            .collect();

        for file_plan in matching_files {
            if file_plan.entity_ids.is_empty() {
                continue;
            }
            let filename = file_plan.filename.display().to_string();
            lines.push(format!("{pcc_token}:{filename}"));
        }

        // Also check exact match (already covered above, but drop the redundant lookup).
        let _ = file_by_suffix;
    }

    lines.push(String::new());
    lines.join("\n")
}
